#!/usr/bin/env python3
"""Build the English home page (en/index.html) from the zh-Hant source (index.html).

index.html is the single source of truth. Every visible string carries its English twin in
data-en (text) or data-en-html (markup); images and labels use data-en-<attr> (data-en-src,
data-en-alt, data-en-href, data-en-hreflang, data-en-lang, and data-en-aria for aria-label).
This script bakes those into a real English page, translates the <head> from HEAD_EN below,
rewrites relative links so they resolve from /en/, and regenerates the FAQPage JSON-LD of both
pages from the #faq markup (so the structured data can never drift from the visible answers).

    python scripts/build_en.py           # write en/index.html (and the zh FAQ JSON-LD in index.html)
    python scripts/build_en.py --check   # exit 1 if either file is stale; writes nothing

Standard library only. Output is deterministic: same index.html in, same bytes out.
"""
import argparse
import hashlib
import html
import json
import re
import sys
from html.parser import HTMLParser
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "index.html"
OUT = ROOT / "en" / "index.html"
SITE = "https://piankeapp.github.io"

# The banner carries a hash of the source, so ANY edit to index.html (even a zh-only one whose English
# twin is unchanged) marks en/index.html stale: the pre-commit hook then asks for a rebuild, which is
# the moment to check that the edited copy's data-en twin still matches.
BANNER = ("<!-- GENERATED by scripts/build_en.py from /index.html (source sha256 {sha}). Do not edit this "
          "file: change index.html (data-en* attributes) and re-run the script. -->\n")

TITLE_EN = "Pianke — Offline Business Card Scanner"
# (attribute, value) of a <meta>/<link> in index.html -> English replacement for its content/href
HEAD_EN = {
    ("name", "description"): "Pianke is a business card scanner that runs entirely on your phone, for Android "
                             "and iPhone / iPad. Scan, recognize, organize and export — your cards never leave "
                             "the device.",
    ("property", "og:title"): "Pianke — Offline business card scanner (Android / iPhone / iPad)",
    ("property", "og:description"): "A business card scanner that works entirely on your phone: no account, no "
                                    "upload, no subscription. Free on Google Play and the App Store.",
    ("property", "og:url"): f"{SITE}/en/",
    ("property", "og:site_name"): "Pianke",
    ("property", "og:locale"): "en_US",
    ("property", "og:locale:alternate"): "zh_TW",
    ("rel", "canonical"): f"{SITE}/en/",
}

# JSON-LD (the main block): English names/descriptions keyed by @type (+ operatingSystem prefix)
LD_EN = {
    "Organization": {"name": "Pianke", "alternateName": "片刻 Pianke"},
    ("MobileApplication", "iOS"): {
        "name": "Pianke", "alternateName": "片刻 Pianke",
        "description": "A fully offline business card scanner: no account, no upload, no subscription. "
                       "OCR and field parsing run on the device."},
    ("MobileApplication", "Android"): {
        "name": "Pianke", "alternateName": "片刻 Pianke",
        "description": "A fully offline business card scanner: no internet permission, no account, "
                       "no subscription."},
}

VOID = {"area", "base", "br", "col", "embed", "hr", "img", "input", "link", "meta", "param", "source",
        "track", "wbr"}
URL_ATTRS = {"href", "src", "poster", "data-poster"}
ABSOLUTE = re.compile(r"^(#|/|\.\./|[a-zA-Z][a-zA-Z0-9+.-]*:)")
LD_RE = re.compile(r'(<script type="application/ld\+json"( id="faq-ld")?>\n)(.*?)(\n</script>)', re.S)


def esc_attr(v):
    return html.escape(v, quote=True)


def build_tag(tag, attrs, self_closing=False):
    parts = [tag]
    for k, v in attrs:
        parts.append(k if v is None else f'{k}="{esc_attr(v)}"')
    return "<" + " ".join(parts) + (" />" if self_closing else ">")


class Translator(HTMLParser):
    """Stream index.html back out, swapping in English and re-rooting relative URLs for /en/."""

    def __init__(self, banner):
        super().__init__(convert_charrefs=False)
        self.banner = banner
        self.out = []
        self.skip = 0          # >0 while inside an element whose content was replaced
        self.used = set()      # HEAD_EN keys actually applied (all must be)
        self.title_done = False

    def emit(self, text):
        if not self.skip:
            self.out.append(text)

    def _attrs(self, tag, attrs):
        d = dict(attrs)
        changed = False
        new = []
        en_text = en_html = None
        swaps = {}
        for k, v in attrs:
            if k == "data-en":
                en_text, changed = v, True
            elif k == "data-en-html":
                en_html, changed = v, True
            elif k.startswith("data-en-"):
                name = k[len("data-en-"):]
                swaps["aria-label" if name == "aria" else name] = v
                changed = True
        for k, v in attrs:
            if k.startswith("data-en"):
                continue
            if k in swaps:
                v = swaps.pop(k)
                changed = True
            if k in URL_ATTRS and v and not ABSOLUTE.match(v):
                v = "../" + v
                changed = True
            if tag == "html" and k == "lang":
                v, changed = "en", True
            new.append((k, v))
        for k, v in swaps.items():  # data-en-<attr> without a zh counterpart
            new.append((k, v))
        # head translations
        for key in (("name", d.get("name")), ("property", d.get("property")), ("rel", d.get("rel"))):
            if key in HEAD_EN and tag in ("meta", "link"):
                target = "content" if tag == "meta" else "href"
                new = [(k, HEAD_EN[key] if k == target else v) for k, v in new]
                self.used.add(key)
                changed = True
        return new, changed, en_text, en_html

    def handle_decl(self, decl):
        self.emit(f"<!{decl}>")
        if decl.lower().startswith("doctype"):
            self.emit("\n" + self.banner.rstrip("\n"))

    def handle_starttag(self, tag, attrs):
        if self.skip:
            if tag not in VOID:
                self.skip += 1
            return
        new, changed, en_text, en_html = self._attrs(tag, attrs)
        self.emit(build_tag(tag, new) if changed else self.get_starttag_text())
        if tag == "title":
            self.emit(html.escape(TITLE_EN, quote=False))
            self.title_done = True
            self.skip = 1
        elif en_html is not None:
            self.emit(en_html)
            self.skip = 1
        elif en_text is not None:
            self.emit(html.escape(en_text, quote=False))
            self.skip = 1
        if self.skip and tag in VOID:
            raise ValueError(f"data-en on void element <{tag}> at {self.getpos()}")

    def handle_startendtag(self, tag, attrs):
        if self.skip:
            return
        new, changed, en_text, en_html = self._attrs(tag, attrs)
        if en_text is not None or en_html is not None:
            raise ValueError(f"data-en on self-closing <{tag}> at {self.getpos()}")
        self.emit(build_tag(tag, new, self_closing=True) if changed else self.get_starttag_text())

    def handle_endtag(self, tag):
        if self.skip:
            if tag in VOID:
                return
            self.skip -= 1
            if self.skip:
                return
        self.emit(f"</{tag}>")

    def handle_data(self, data):
        self.emit(data)

    def handle_entityref(self, name):
        self.emit(f"&{name};")

    def handle_charref(self, name):
        self.emit(f"&#{name};")

    def handle_comment(self, data):
        self.emit(f"<!--{data}-->")

    def handle_pi(self, data):
        self.emit(f"<?{data}>")


class FaqReader(HTMLParser):
    """Collect (question, answer) text from <details class="qa"> inside the page."""

    def __init__(self):
        super().__init__(convert_charrefs=True)
        self.items, self.mode, self.buf = [], None, []
        self.depth = 0

    def handle_starttag(self, tag, attrs):
        cls = (dict(attrs).get("class") or "").split()
        if tag == "summary":
            self.mode, self.buf = "q", []
        elif tag == "div" and "a" in cls:
            self.mode, self.buf, self.depth = "a", [], 1
        elif self.mode == "a" and tag == "div":
            self.depth += 1

    def handle_endtag(self, tag):
        if self.mode == "q" and tag == "summary":
            self.items.append([norm(self.buf), None])
            self.mode = None
        elif self.mode == "a" and tag == "div":
            self.depth -= 1
            if not self.depth:
                self.items[-1][1] = norm(self.buf)
                self.mode = None

    def handle_data(self, data):
        if self.mode:
            self.buf.append(data)


def norm(parts):
    return re.sub(r"\s+", " ", "".join(parts)).strip()


def faq_jsonld(page_html):
    r = FaqReader()
    r.feed(page_html)
    items = [(q, a) for q, a in r.items if q and a]
    if not items:
        raise ValueError("no FAQ items found in #faq")
    data = {
        "@context": "https://schema.org",
        "@type": "FAQPage",
        "mainEntity": [{"@type": "Question", "name": q,
                        "acceptedAnswer": {"@type": "Answer", "text": a}} for q, a in items],
    }
    return json.dumps(data, ensure_ascii=False, indent=2)


def set_faq_ld(page_html):
    body = faq_jsonld(page_html)
    n = 0

    def sub(m):
        nonlocal n
        if not m.group(2):
            return m.group(0)
        n += 1
        return m.group(1) + body + m.group(4)

    out = LD_RE.sub(sub, page_html)
    if n != 1:
        raise ValueError(f'expected exactly one <script id="faq-ld"> block, found {n}')
    return out


def english_main_ld(page_html):
    def sub(m):
        if m.group(2):
            return m.group(0)
        data = json.loads(m.group(3))
        for item in data if isinstance(data, list) else [data]:
            t = item.get("@type")
            key = t if t in LD_EN else (t, (item.get("operatingSystem") or "").split()[0])
            item.update(LD_EN.get(key, {}))
        return m.group(1) + json.dumps(data, ensure_ascii=False, indent=2) + m.group(4)

    return LD_RE.sub(sub, page_html)


def build(src_text):
    zh = set_faq_ld(src_text)
    t = Translator(BANNER.format(sha=hashlib.sha256(zh.encode("utf-8")).hexdigest()[:16]))
    t.feed(zh)
    t.close()
    missing = set(HEAD_EN) - t.used
    if missing or not t.title_done:
        raise ValueError(f"index.html head lacks tags for: {sorted(missing)}{'' if t.title_done else ' + <title>'}")
    en = "".join(t.out)
    en = english_main_ld(en)
    en = set_faq_ld(en)
    return zh, en


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--check", action="store_true", help="exit 1 if outputs are stale; write nothing")
    args = ap.parse_args()
    src = SRC.read_text(encoding="utf-8")
    zh, en = build(src)
    stale = []
    if zh != src:
        stale.append("index.html (FAQ JSON-LD)")
    if not OUT.exists() or OUT.read_text(encoding="utf-8") != en:
        stale.append("en/index.html")
    if args.check:
        if stale:
            print("stale: " + ", ".join(stale) + " - run: python scripts/build_en.py", file=sys.stderr)
            return 1
        print("en/index.html is up to date")
        return 0
    if zh != src:
        SRC.write_text(zh, encoding="utf-8", newline="")
    if "en/index.html" in stale:
        OUT.parent.mkdir(exist_ok=True)
        OUT.write_text(en, encoding="utf-8", newline="")
    print("wrote " + (", ".join(stale) if stale else "nothing (already up to date)"))
    return 0


if __name__ == "__main__":
    sys.exit(main())
